apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::193180914360:user/github-action-user
      username: github-action-user
      groups:
        - system:masters