name: frontend-cd

on:
  push:
    branches:
      - 'master'
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  linting_job:
    name: Linting job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NVM
        run: nvm install 18
      - run: nvm use
      - name: Install packages
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  test_job:
    name: Test job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run test
        run: npm run test
  build_job:
    name: Build job
    env:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: 193180914360
      EKS_CLUSTER: cluster
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    needs:
      - linting_job
      - test_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Verify identity
        run: aws sts get-caller-identity
      - name: Login to AWS ECR  
        uses: aws-actions/amazon-ecr-login@v2
      - name: Extract git tag
        run: echo "GIT_SHA=$(git rev-parse master)" >> $GITHUB_ENV
      - name: Verify git tag content
        run: echo $GIT_SHA
      - name: Build image
        run: docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:$GIT_SHA --build-arg REACT_APP_MOVIE_API_URL=http://localhost:5000 .
      - name: Deploy image
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:$GIT_SHA
      - name: Config kubectl to connect to AWS EKS Cluster
        run: aws eks update-kubeconfig --name $EKS_CLUSTER
      - name: Deploy application
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml