name: frontend-ci

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  linting_job:
    name: Linting job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  test_job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run test
        run: npm run test
  build_job:
    name: Build job
    runs-on: ubuntu-latest
    needs:
      - linting_job
      - test_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build code
        run : |
          docker build -t frontend-ci-build .
      - name: Test code
        run: npm run test