name: frontend-ci

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  linting_job:
    name: Linting job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        run: |
          sudo apt update
          sudo apt install nodejs
      - name: Install packages
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  test_job:
    name: Test job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        run: |
          sudo apt update
          sudo apt install nodejs
      - name: Install packages
        run: npm ci
      - name: Run test
        run: npm run test
  build_job:
    name: Build job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    needs:
      - linting_job
      - test_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nodejs
        run: |
          sudo apt update
          sudo apt install nodejs
      - name: Install packages
        run: npm ci
      - name: Build code
        run : |
          docker build -t frontend-ci-build .
      - name: Test code
        run: npm run test